### ISSUE TITLE
RemoveDiacritics does not deal well with certain characters

### ISSUE THREAD

**Issue by Poltuu** [LuccaSA/NExtends#3]
Precisely ØøæÆœŒ

**Comment by nfaugout** [comment]
It seems that theses symbols are not diacritics.

Maybe you could super charge the method with something like RemoveSpecialCharacters, that call RemoveDiacritics, and then remove additional special characters like these.

What do you think ?

**Comment by Poltuu** [comment]
does not work in my case, where i wish those to be replaced like this;
 - Œ ->"OE"
and so on.
RemoveSpecialCharacters actually remove those, so not good here

**Comment by nfaugout** [comment]
OK, you need something like SanitiezSpecialCharacters then, that remove diacritics and make some replaces for theses special double-characters
