### ISSUE TITLE
Ellipsis should be counted for the total number of characters in `Truncate`

### ISSUE THREAD

**Issue by GMouron** [LuccaSA/NExtends#69]
Use case : I have a db column with 255 chars length. I therefore ensure that my string fits with doing mystring.truncate(255).

Problem : The addition of ellipsis being true by default, the current implementation truncate to 255 AND THEN add the ellipsis, making it 258 characters. The insert in my db fails.

https://github.com/LuccaSA/NExtends/blob/5afb046ad1567de48fa0f5d2251110de3fe6e336/NExtends/Primitives/Strings/String.extensions.cs#L192

Solution : Taking into account the length of the ellipsis by truncating with (maxLength - sizeof(ellipsis)).

This does not break the api and won't affect negatively existing usage (I would even say would affect positively).

I can take care of the implementation if you agree.

**Comment by Poltuu** [comment]
yeah definitely. that's a bug

**Comment by GMouron** [comment]
I was apparently pointing at an old release of NExtends, this is currently correctly implemented : https://github.com/LuccaSA/NExtends/blob/5afb046ad1567de48fa0f5d2251110de3fe6e336/NExtends/Primitives/Strings/String.extensions.cs#L193

Sorry.
